=== L2jOpenSource/L2jOpenSource/H5/L2jReunion/L2jReunion_2014_07_14/L2J_ReunionProject_Data/dist/game/data/xsd/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="item" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="ingredient" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="maintainIngredient" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="production" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="count" type="xs:positiveInteger" use="required" />
									<xs:attribute name="id" type="xs:integer" use="required" />
									<xs:attribute name="enchantmentLevel" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="applyTaxes" type="xs:boolean" />
			<xs:attribute name="maintainEnchantment" type="xs:boolean" />
			<xs:attribute name="useRate" type="xs:token" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== L2jOpenSource/L2jOpenSource/H5/L2jReunion/L2jReunion_2014_07_14/L2J_ReunionProject_Data/dist/game/data/multisell/364820002.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Human Mercenary -->
		<production count="1" id="13581" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Elf Mercenary -->
		<production count="1" id="13582" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Dark Elf Mercenary -->
		<production count="1" id="13583" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Orc Mercenary -->
		<production count="1" id="13584" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Dwarf Mercenary -->
		<production count="1" id="13585" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13200" id="57" />
		<!-- Transformation Scroll: Dion Kamael Mercenary -->
		<production count="1" id="13586" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="70000" id="57" />
		<!-- Dion Disguise Scroll -->
		<production count="1" id="13678" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="27800" id="57" />
		<!-- Dion Territory Badge -->
		<ingredient count="5" id="13758" />
		<!-- Transformation Scroll: Dion Archer Mercenary -->
		<production count="1" id="13588" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="27800" id="57" />
		<!-- Dion Territory Badge -->
		<ingredient count="5" id="13758" />
		<!-- Transformation Scroll: Dion Wizard Mercenary -->
		<production count="1" id="13589" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="27800" id="57" />
		<!-- Dion Territory Badge -->
		<ingredient count="5" id="13758" />
		<!-- Transformation Scroll: Dion Kamael Captain Mercenary -->
		<production count="1" id="13590" />
	</item>
	<item>
		<!-- Adena -->
		<ingredient count="13900" id="57" />
		<!-- Dion Territory Badge -->
		<ingredient count="16" id="13758" />
		<!-- Red Talisman - Territory Guard -->
		<production count="1" id="14605" />
	</item>
</list>

=== L2jOpenSource/L2jOpenSource/H5/L2jMaster_org/L2jMaster_org_2019_07_02/L2JMaster_DataPack/dist/game/data/multisell/203.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/multisell.xsd">
	<npcs>
		<npc>31756</npc> <!-- Mr. Cat (Test Server Helper) -->
		<npc>31757</npc> <!-- Miss Queen (Test Server Helper) -->
	</npcs>
	<item>
		<!-- Gludio Territory Badge -->
		<ingredient count="30" id="13757" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Dion Territory Badge -->
		<ingredient count="30" id="13758" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Giran Territory Badge -->
		<ingredient count="30" id="13759" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Oren Territory Badge -->
		<ingredient count="30" id="13760" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Aden Territory Badge -->
		<ingredient count="30" id="13761" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Innadril Territory Badge -->
		<ingredient count="30" id="13762" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Goddard Territory Badge -->
		<ingredient count="30" id="13763" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Rune Territory Badge -->
		<ingredient count="30" id="13764" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Schuttgart Territory Badge -->
		<ingredient count="30" id="13765" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
	<item>
		<!-- Olympiad Token -->
		<ingredient count="5000" id="13722" />
		<!-- Emery Piece -->
		<ingredient count="5" id="13749" />
		<!-- Gracian Anniversary Coins  -->
		<production count="1" id="13693" />
	</item>
</list>
